######################################################################
# Automatically generated by qmake (2.01a) Thu Oct 4 19:01:12 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
SOURCES += glee/GLee.c
SOURCES += glwidget.cpp
SOURCES += mainwindow.cpp
SOURCES +=

HEADERS += glwidget.h \
    rtiutil.h
HEADERS += mainwindow.h
HEADERS +=

QT += opengl
